### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by felixschlegel**
### Motivation:

This PR closes issue #28.

### Modifications:

* add instructions on how to build `librdkafka` from source
* add documentation for the public interface

### CODE REVIEW

**Comment by felixschlegel** [comment]
(Note to self) I accidentally used the wrong indentation for the code examples, will fix it soon.

**Comment by freef4ll** [comment]
Just to note that Confluent (the company behind Kafka), provide x86_64 packages for librdkafka that are [more up to date](https://docs.confluent.io/platform/current/clients/index.html#librdkafka-and-derived-clients) than Ubuntu Focal release for example.

This would be present in the [clients repo](https://docs.confluent.io/platform/current/installation/installing_cp/deb-ubuntu.html#configure-cp).

**Comment by FranzBusch** [comment]
@felixschlegel I think that is a good point that @freef4ll provided here. Cold you check if these are working? Might be easier than building librdkafka from source.

**Comment by felixschlegel** [comment]
Hey @freef4ll, Hey @FranzBusch,

first of all, I want to apologise for replying to your messages so late — I was quite busy last week.

Thanks for raising that issue, unfortunately, I am not very much of an expert with `apt-get` which led to me thinking that building the library from source would be the easiest path to choose.

If you have a look at [this commit](https://github.com/swift-server/swift-kafka-gsoc/pull/40/commits/b0a0cfa4d5bcb737b68c07f2a6cbb5227448ef0d), you can see that I now use the installation recommended by Confluent both in the `Dockerfile` as well as in the new `README`.

I still have two things that I am curious about:

* The installation process did not work on `focal`. However, it works for `jammy` so I updated our `Dockerfile`. Running on `focal` resulted in the following error:
  ```bash
  > [5/8] RUN add-apt-repository "deb http://packages.confluent.io/deb/ $(lsb_release -cs) main" -y:
  #0 0.447 Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
  #0 0.466 Get:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
  #0 0.564 Get:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease [108 kB]
  #0 0.603 Get:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease [114 kB]
  #0 1.029 Ign:5 http://packages.confluent.io/deb focal InRelease
  #0 1.697 Err:6 http://packages.confluent.io/deb focal Release
  #0 1.697   404  Not Found [IP: 99.84.88.118 80]
  #0 1.707 Reading package lists...
  #0 2.111 E: The repository 'http://packages.confluent.io/deb focal Release' does not have a Release file.
  ```
* You said, that the Confluence `librdkafka` does not work for `ARM64`, however, it seemed to work perfectly fine when running inside of Docker on my Apple Silicon machine. Maybe I am missing something about Docker or Rosetta here, just wanted to double-check with you

**Pull request merged**
